name: Build & Push the Docker image

on:
  push:
    tags: ['*']

env:
  DOCKER_GCS_IMAGE_URL: ${{ env.GCS_DOCKER_REGISTRY }}/${{ env.GCS_PROJECT_ID }}/${{ env.GCS_DOCKER_IMAGE_NAME }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Github Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCS_CREDENTIALS_JSON }}

      - name: Log in to Google Cloud Artifact registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.GCS_DOCKER_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          push: true
          context: .
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
            ${{ DOCKER_GCS_IMAGE_URL }}:${{ github.ref_name }}
            ${{ DOCKER_GCS_IMAGE_URL }}:latest
